/** 宋刻书斋：古籍页支持站内篇章筛选与维基文库公开全文检索，并记录个人阅读进度。 */
import { BookOpen, ChevronRight, ExternalLink, Search } from "lucide-react";
import { useEffect, useState } from "react";
import { useSearch } from "wouter";
import { useAuth } from "@/_core/hooks/useAuth";
import { startLogin } from "@/const";
import { PageMasthead } from "@/components/SiteChrome";
import { ExternalSource, InkStamp, RuleLabel } from "@/components/StudyElements";
import { AiStudyAssistant } from "@/components/AiStudyAssistant";
import { StudyMargin } from "@/components/StudyMargin";
import { trpc } from "@/lib/trpc";
import { toast } from "sonner";

export default function Classics() {
  const { isAuthenticated } = useAuth(); const utils = trpc.useUtils();
  const search = useSearch(); const initialQuery = new URLSearchParams(search).get("q") ?? "";
  const preferredChapterTitle = new URLSearchParams(search).get("chapter");
  const [query, setQuery] = useState(initialQuery); const [category, setCategory] = useState(""); const [selectedId, setSelectedId] = useState<number | null>(null); const [fullTextQuery, setFullTextQuery] = useState(initialQuery); const [submittedQuery, setSubmittedQuery] = useState(initialQuery);
  useEffect(() => { const nextQuery = new URLSearchParams(search).get("q") ?? ""; setQuery(nextQuery); setFullTextQuery(nextQuery); setSubmittedQuery(nextQuery); setSelectedId(null); }, [search]);
  const filters = trpc.catalog.filters.useQuery(); const classicsQuery = trpc.catalog.classics.useQuery({ query: query || undefined, category: category || undefined });
  const records = classicsQuery.data ?? []; const selected = records.find((record) => record.id === selectedId) ?? records[0];
  const chaptersQuery = trpc.catalog.chapters.useQuery({ classicId: selected?.id ?? 0 }, { enabled: Boolean(selected) });
  const fullTextResults = trpc.catalog.wikisourceSearch.useQuery({ query: submittedQuery || "中医" }, { enabled: Boolean(submittedQuery) });
  const progressMutation = trpc.study.progress.set.useMutation({ onSuccess: () => { void utils.study.desk.invalidate(); toast.success("阅读进度已记入书案"); } });
  return <main className="inner-page"><PageMasthead index="丙 · 古籍文献" title="从一段原文，回到一部书" lead="先用站内目录定位篇章，再按关键词检索维基文库公开原文。" />
    <section className="catalog-controls classic-controls"><label className="catalog-search"><Search size={18} /><span className="sr-only">搜索古籍目录</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="检索书名、作者、类别或简介" /></label><label className="facet-select"><span>类别</span><select value={category} onChange={(event) => setCategory(event.target.value)}><option value="">不限</option>{(filters.data?.classicCategories ?? []).map((item) => <option key={item}>{item}</option>)}</select></label><p>{classicsQuery.isLoading ? "正在整理书目……" : `共得 ${records.length} 部典籍`}<button type="button" onClick={() => { setQuery(""); setCategory(""); }}>清除筛选</button></p></section>
    <section className={`archive-layout ${classicsQuery.isLoading || chaptersQuery.isLoading ? "is-loading" : ""}`} aria-busy={classicsQuery.isLoading || chaptersQuery.isLoading}><aside className="archive-spine" aria-label="古籍目录"><div className="archive-spine-heading"><BookOpen size={20} strokeWidth={1.4} /><div><RuleLabel>藏书目录</RuleLabel><h2>医籍索引</h2></div></div><div className="classic-tabs">{classicsQuery.isLoading && !records.length ? Array.from({ length: 4 }, (_, index) => <div className="classic-tab skeleton-row" key={index}><span /><div><b /><small /></div></div>) : records.map((classic, index) => <button key={classic.id} type="button" className={selected?.id === classic.id ? "classic-tab active" : "classic-tab"} onClick={() => setSelectedId(classic.id)}><span>{String(index + 1).padStart(2, "0")}</span><div><b>{classic.title}</b><small>{classic.era} · {classic.category}</small></div><ChevronRight size={16} /></button>)}{!records.length && !classicsQuery.isLoading ? <p className="empty-note">当前筛选没有书目。</p> : null}</div></aside>{selected ? <ClassicLeaf classic={selected} chapters={chaptersQuery.data ?? []} preferredChapterTitle={preferredChapterTitle} onProgress={(progressPercent, chapterId) => { if (!isAuthenticated) return startLogin(); progressMutation.mutate({ classicId: selected.id, chapterId, progressPercent }); }} /> : classicsQuery.isLoading ? <div className="empty-leaf detail-skeleton"><p>正在展开古籍目录……</p></div> : <div className="empty-leaf"><p>从左侧目录选择一部医籍。</p></div>}</section>
    <section className="source-search"><div><RuleLabel>公开全文检索</RuleLabel><h2>在维基文库中寻一段原文</h2><p>结果来自中文维基文库公开接口；本站只显示标题、摘要与原站链接，便于回到原典继续阅读。</p></div><form onSubmit={(event) => { event.preventDefault(); setSubmittedQuery(fullTextQuery.trim()); }}><input value={fullTextQuery} onChange={(event) => setFullTextQuery(event.target.value)} placeholder="例如：伤寒论、桂枝汤、痰饮" /><button type="submit">检索原文</button></form>{fullTextResults.isFetching ? <p className="source-search-status">正在查询公开文献……</p> : null}<div className="source-result-list">{fullTextResults.data?.map((item) => <a href={item.sourceUrl} target="_blank" rel="noreferrer" key={item.pageId}><span>公开原典</span><b>{item.title}</b><p>{item.snippet}</p><small>{new Date(item.timestamp).toLocaleDateString("zh-CN")}</small><ExternalLink size={15} /></a>)}</div></section>
  </main>;
}

type ClassicRecord = { id: number; title: string; era: string | null; author: string | null; category: string | null; summary: string | null; sourceUrl: string; };
type ChapterRecord = { id: number; title: string; excerpt: string | null; };
function ClassicLeaf({ classic, chapters, preferredChapterTitle, onProgress }: { classic: ClassicRecord; chapters: ChapterRecord[]; preferredChapterTitle: string | null; onProgress: (progress: number, chapterId?: number) => void }) { const [activeChapterId, setActiveChapterId] = useState<number | undefined>(undefined); useEffect(() => { const match = preferredChapterTitle ? chapters.find((chapter) => chapter.title === preferredChapterTitle) : undefined; setActiveChapterId(match?.id); }, [chapters, preferredChapterTitle, classic.id]); const activeChapter = chapters.find((chapter) => chapter.id === activeChapterId) ?? chapters[0]; return <article className="classic-leaf paper-noise"><div className="leaf-head"><span>卷 · 文献研读</span><span>{classic.era}</span></div><div className="leaf-title"><div><p className="eyebrow">{classic.category}</p><h2>{classic.title}</h2><p className="leaf-author">{classic.author}</p></div><InkStamp>阅</InkStamp></div><p className="classic-summary">{classic.summary}</p><div className="chapter-block"><RuleLabel>篇章索引</RuleLabel><ol>{chapters.map((chapter) => <li key={chapter.id}><button type="button" className={activeChapter?.id === chapter.id ? "chapter-select active" : "chapter-select"} onClick={() => setActiveChapterId(chapter.id)}>{chapter.title}</button></li>)}</ol></div>{activeChapter ? <div className="passage-block"><RuleLabel>章节摘录</RuleLabel><blockquote>“{activeChapter.excerpt}”</blockquote><div className="progress-actions"><span>读至此处</span><button type="button" onClick={() => onProgress(35, activeChapter.id)}>标记为 35%</button><button type="button" onClick={() => onProgress(70, activeChapter.id)}>标记为 70%</button><button type="button" onClick={() => onProgress(100, activeChapter.id)}>本篇读毕</button></div></div> : null}<ExternalSource href={classic.sourceUrl}>前往公开原文阅览页 <ExternalLink size={14} /></ExternalSource><AiStudyAssistant context={{ kind: "古籍章节", title: activeChapter ? `${classic.title} · ${activeChapter.title}` : classic.title, sourceTitle: `《${classic.title}》`, excerpt: activeChapter?.excerpt ?? undefined, studyNote: classic.summary ?? undefined }} /><StudyMargin resourceType="classic" resourceId={classic.id} resourceTitle={classic.title} /></article>; }
