/** 宋刻书斋：登录后以内置账户布局承载个人收藏、笔记、目标与续读提醒。 */
import { Award, BellRing, Bookmark, Flag, NotebookPen, ScrollText } from "lucide-react";
import { FormEvent, useMemo, useState } from "react";
import { trpc } from "@/lib/trpc";
import { Link } from "wouter";

const metricLabels = { path_steps: "学习路线步骤", reading_entries: "古籍续读条目", study_notes: "研读笔记" } as const;

export default function StudyDesk() {
  const utils = trpc.useUtils();
  const desk = trpc.study.desk.useQuery();
  const overview = trpc.study.overview.useQuery();
  const goals = trpc.study.goals.list.useQuery();
  const reminders = trpc.study.reminders.list.useQuery();
  const [goalTitle, setGoalTitle] = useState(""); const [goalMetric, setGoalMetric] = useState<keyof typeof metricLabels>("path_steps"); const [goalTarget, setGoalTarget] = useState("3"); const [goalDeadline, setGoalDeadline] = useState("");
  const [reminderTitle, setReminderTitle] = useState(""); const [reminderGoalId, setReminderGoalId] = useState(""); const [reminderInterval, setReminderInterval] = useState("7"); const [reminderHour, setReminderHour] = useState(() => String(new Date().getHours()));
  const data = desk.data; const metrics = overview.data;
  const activeGoals = useMemo(() => goals.data?.filter((goal) => goal.status === "active") ?? [], [goals.data]);
  const refresh = async () => { await Promise.all([utils.study.goals.list.invalidate(), utils.study.reminders.list.invalidate(), utils.study.overview.invalidate()]); };
  const createGoal = trpc.study.goals.create.useMutation({ onSuccess: async () => { setGoalTitle(""); setGoalTarget("3"); setGoalDeadline(""); await refresh(); } });
  const archiveGoal = trpc.study.goals.archive.useMutation({ onSuccess: refresh });
  const createReminder = trpc.study.reminders.create.useMutation({ onSuccess: async () => { setReminderTitle(""); setReminderGoalId(""); await refresh(); } });
  const updateReminder = trpc.study.reminders.update.useMutation({ onSuccess: refresh });
  const deleteReminder = trpc.study.reminders.delete.useMutation({ onSuccess: refresh });
  const markReminderSeen = trpc.study.reminders.markSeen.useMutation({ onSuccess: () => utils.study.reminders.list.invalidate() });

  function submitGoal(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!goalTitle.trim()) return; createGoal.mutate({ title: goalTitle.trim(), metric: goalMetric, targetCount: Number(goalTarget), deadlineAt: goalDeadline ? new Date(`${goalDeadline}T23:59:59`) : null }); }
  function submitReminder(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!reminderTitle.trim()) return; createReminder.mutate({ title: reminderTitle.trim(), goalId: reminderGoalId ? Number(reminderGoalId) : null, intervalDays: Number(reminderInterval), hourLocal: Number(reminderHour) }); }

  return <div className="desk-page">
    <header><p>我的书案</p><h1>书签、朱批与续读</h1><span>所有记录仅归当前登录用户所有。</span></header>
    <section className="desk-overview" aria-label="学习成就概览"><div><p>研读概览</p><h2>将零散书页，续成自己的阅读次第。</h2></div><Award size={28} strokeWidth={1.25} /><div className="desk-overview-metrics"><span><b>{metrics?.completedPathCount ?? 0}/3</b><small>已完成路线</small></span><span><b>{metrics?.averageReadingProgress ?? 0}%</b><small>平均阅读</small></span><span><b>{(metrics?.savedCount ?? 0) + (metrics?.noteCount ?? 0)}</b><small>书签与朱批</small></span></div></section>
    <section className="learning-planning-grid" aria-label="学习计划与复习提醒">
      <section className="planning-panel"><div className="desk-section-title"><Flag size={18} /><h2>自定学习目标</h2><span>{activeGoals.length}</span></div><p className="planning-intro">目标会按实际完成的学习路线步骤、古籍续读条目或研读笔记自动统计，不额外写入阅读记录。</p><form className="planning-form" onSubmit={submitGoal}><input value={goalTitle} onChange={(event) => setGoalTitle(event.target.value)} maxLength={255} placeholder="例如：完成三条桂枝路线步骤" required /><div><label>统计对象<select value={goalMetric} onChange={(event) => setGoalMetric(event.target.value as keyof typeof metricLabels)}>{Object.entries(metricLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label>目标数量<input value={goalTarget} onChange={(event) => setGoalTarget(event.target.value)} type="number" min="1" max="365" required /></label></div><label>截止日期（可选）<input value={goalDeadline} onChange={(event) => setGoalDeadline(event.target.value)} type="date" /></label><button type="submit" disabled={createGoal.isPending}>立下目标</button></form><div className="goal-list">{activeGoals.map((goal) => { const percent = Math.min(100, Math.round((goal.currentCount / goal.targetCount) * 100)); return <article key={goal.id} className="goal-row"><div><b>{goal.title}</b><small>{metricLabels[goal.metric]} · {goal.currentCount}/{goal.targetCount}{goal.deadlineAt ? ` · 截止 ${new Date(goal.deadlineAt).toLocaleDateString("zh-CN")}` : ""}</small><i><em style={{ width: `${percent}%` }} /></i></div><span>{goal.completed ? "已达成" : `${percent}%`}</span><button type="button" onClick={() => archiveGoal.mutate({ id: goal.id })}>归档</button></article>; })}{!activeGoals.length ? <p className="desk-empty">设定一个可量化的目标，让路线、续读与笔记形成可见的累积。</p> : null}</div></section>
      <section className="planning-panel"><div className="desk-section-title"><BellRing size={18} /><h2>定期复习提醒</h2><span>{reminders.data?.reminders.length ?? 0}</span></div><p className="planning-intro">提醒在指定的本地小时执行检查；到期后会在此书案留下待复习提示，未配置时不会创建任何外部提醒。</p>{reminders.data?.pending.length ? <div className="review-inbox">{reminders.data.pending.map((item) => <div key={item.id}><span>待复习</span><b>{item.title}</b><small>{item.goalTitle ?? "独立复习主题"} · {new Date(item.dueAt).toLocaleDateString("zh-CN")}</small><button type="button" onClick={() => markReminderSeen.mutate({ eventId: item.id })}>标为已阅</button></div>)}</div> : null}<form className="planning-form" onSubmit={submitReminder}><input value={reminderTitle} onChange={(event) => setReminderTitle(event.target.value)} maxLength={255} placeholder="例如：回顾本周伤寒论条文" required /><div><label>关联目标<select value={reminderGoalId} onChange={(event) => setReminderGoalId(event.target.value)}><option value="">不关联目标</option>{activeGoals.map((goal) => <option key={goal.id} value={goal.id}>{goal.title}</option>)}</select></label><label>每隔几日<input value={reminderInterval} onChange={(event) => setReminderInterval(event.target.value)} type="number" min="1" max="60" required /></label></div><label>本地提醒时刻<select value={reminderHour} onChange={(event) => setReminderHour(event.target.value)}>{Array.from({ length: 24 }, (_, hour) => <option value={hour} key={hour}>{String(hour).padStart(2, "0")}:00</option>)}</select></label><button type="submit" disabled={createReminder.isPending}>设置提醒</button></form><div className="reminder-list">{reminders.data?.reminders.map((reminder) => <article key={reminder.id} className="reminder-row"><div><b>{reminder.title}</b><small>{reminder.goalTitle ?? "独立复习主题"} · 每 {reminder.intervalDays} 日 · {String((reminder.hourUtc + 8) % 24).padStart(2, "0")}:00</small><small>下次检查：{new Date(reminder.nextReviewAt).toLocaleString("zh-CN")}</small></div><button type="button" onClick={() => updateReminder.mutate({ id: reminder.id, title: reminder.title, goalId: reminder.goalId, intervalDays: reminder.intervalDays, hourLocal: (reminder.hourUtc + 8) % 24, enabled: !Boolean(reminder.enabled) })}>{reminder.enabled ? "暂停" : "恢复"}</button><button type="button" onClick={() => deleteReminder.mutate({ id: reminder.id })}>删除</button></article>)}{!reminders.data?.reminders.length ? <p className="desk-empty">设置节奏后，站内会在到期时生成一则待复习提示。</p> : null}</div></section>
    </section>
    {desk.isLoading ? <p className="desk-loading">正在铺开你的书案……</p> : <div className="desk-grid">
      <section><div className="desk-section-title"><Bookmark size={18} /><h2>我的收藏</h2><span>{data?.saved.length ?? 0}</span></div>{data?.saved.map((item) => item.resource ? <Link className="desk-row" key={item.id} href={item.resource.href}><b>{item.resource.title}</b><small>{item.resource.kind} · {item.resource.subtitle ?? "学习条目"}</small></Link> : <div className="desk-row" key={item.id}><b>已归档条目</b><small>原始条目已不可用</small></div>)}{!data?.saved.length ? <p className="desk-empty">在任一详情书页点击“收入书签”，收藏会出现在这里。</p> : null}</section>
      <section><div className="desk-section-title"><NotebookPen size={18} /><h2>最近笔记</h2><span>{data?.notes.length ?? 0}</span></div>{data?.notes.slice(0, 6).map((note) => <article className="desk-note" key={note.id}><b>{note.title}</b><p>{note.body}</p><small>{new Date(note.updatedAt).toLocaleString("zh-CN")}</small></article>)}{!data?.notes.length ? <p className="desk-empty">从本草、经方或古籍详情页添加你的第一则研读笔记。</p> : null}</section>
      <section><div className="desk-section-title"><ScrollText size={18} /><h2>续读进度</h2><span>{data?.progress.length ?? 0}</span></div>{data?.progress.map((item) => <Link className="desk-progress" key={item.id} href="/guji"><div><b>{item.classicTitle ?? "古籍研读"}</b><span>{item.progressPercent}%</span></div><small>{item.chapterTitle ? `已读至：${item.chapterTitle}` : "已记录阅读位置"} · {new Date(item.lastReadAt).toLocaleDateString("zh-CN")}</small><i><em style={{ width: `${item.progressPercent}%` }} /></i></Link>)}{!data?.progress.length ? <p className="desk-empty">在古籍阅读页标记读至何处，进度会自动记录。</p> : null}</section>
    </div>}
  </div>;
}
