export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  githubClientId: process.env.GITHUB_CLIENT_ID ?? "",
  githubClientSecret: process.env.GITHUB_CLIENT_SECRET ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  localLlmBaseUrl: process.env.LOCAL_LLM_BASE_URL ?? "",
  localLlmModel: process.env.LOCAL_LLM_MODEL ?? "",
  localLlmApiKey: process.env.LOCAL_LLM_API_KEY ?? "",
  networkLlmBaseUrl: process.env.NETWORK_LLM_BASE_URL ?? "",
  networkLlmModel: process.env.NETWORK_LLM_MODEL ?? "",
  networkLlmApiKey: process.env.NETWORK_LLM_API_KEY ?? "",
};
